// ATS-safe defaults — proper dimensions, neutral colors, standard font
export const ATS_DEFAULTS = {
  font: 'inter',
  fontSize: 'normal',
  fontSizeBase: 11,
  fontSizeNameDelta: 8,
  fontSizeSectionDelta: 1,
  fontSizeEntryDelta: 0,
  lineHeight: 'normal',
  margins: 'normal',
  accentColor: '#374151',
  textColor: '#1a1a1a',
  headingStyle: 'ruled',
  sectionTitleCase: 'upper',
  sectionBorderWidth: 1,
  sectionBorderColor: '',
  headerAlign: 'left',
  headerLayout: 'stack',
  headerInlineGap: 8,
  contactStyle: 'icon',
  contactCols: 1,
  contactLayout: 'justify',
  photoShape: 'circle',
  photoSize: 'md',
  photoBorder: 'accent',
  photoHeight: 'match',
  photoTextAlign: 'center',
  showHeaderBorder: false,
  headerBorderWidth: 2,
  customFont: '',
  iconSize: 11,
  lineHeightValue: 1.5,
  sectionGap: 16,
  itemGap: 12,
  marginH: 18,
  marginV: 14,
  // Template-specific background colors
  sidebarBg: '#1e293b',
  // Header / named-element color overrides (empty = use template default)
  headerTextColor: '#ffffff',
  nameColor: '',
  jobTitleColor: '',
};

export const defaultResumeData = {
  id: 'resume_default',
  name: 'Sairam Gudiputi',
  updatedAt: Date.now(),
  template: 'classic',
  settings: { ...ATS_DEFAULTS, accentColor: '#1a1a1a' },
  personal: {
    name: 'Sairam Gudiputi',
    title: 'Senior Frontend Developer',
    email: 'sairamgudiputi8@gmail.com',
    phone: '+91 8519819953',
    location: 'Hyderabad, India',
    website: 'sairamg.dev',
    linkedin: 'linkedin.com/in/sairamg8',
    github: '',
    summary:
      'Senior Frontend Developer with 7+ years of experience building scalable, high-performance web applications using React, Next.js, and TypeScript. Proven track record delivering accessible, performant user interfaces across fintech, healthcare, and e-commerce domains — improving load times by up to 70% and mentoring engineering teams. Skilled in modern state management, CI/CD, automated testing, and design systems.',
    photo: null,
    hiddenFields: ['github'],
  },
  sections: [
    {
      id: 'skills',
      type: 'skills',
      title: 'Skills',
      settings: {
        spacing: 'normal',
        columns: 1,
        skillsStyle: 'inline',
        separator: 'colon',
        titleStyle: 'inline',
      },
      items: [
        { id: 'sk1', category: 'Frontend Development', skills: 'JavaScript (ES6+), TypeScript, React.js, Next.js 14/15, HTML5, CSS3', description: '', bullets: [] },
        { id: 'sk2', category: 'Backend Development', skills: 'Node.js, Express.js, RESTful APIs, JWT, RBAC (Role-Based Access Control)', description: '', bullets: [] },
        { id: 'sk3', category: 'Development Tools', skills: 'Webpack, Vite, Babel, ESLint, Git, NPM/Yarn', description: '', bullets: [] },
        { id: 'sk4', category: 'Testing & Quality', skills: 'Jest, React Testing Library (RTL), Cypress, Unit Testing', description: '', bullets: [] },
        { id: 'sk5', category: 'UI/UX Libraries', skills: 'Material UI, TailwindCSS, Bootstrap, Chart.js, Ant Design, Shadcn', description: '', bullets: [] },
        { id: 'sk6', category: 'Methodologies', skills: 'Agile/Scrum, CI/CD, Modular Architecture, State Management (Context API, Redux Toolkit)', description: '', bullets: [] },
      ],
    },
    {
      id: 'experience',
      type: 'experience',
      title: 'Experience',
      settings: {
        spacing: 'normal',
        columns: 1,
        showDates: true,
        showLocation: true,
        titleStyle: 'stacked',
      },
      items: [
        {
          id: 'exp1',
          company: 'LTIMindtree',
          role: 'Software Engineer',
          location: '',
          startDate: '09/2024',
          endDate: '',
          current: true,
          description: '<p><strong>RFP Internal AI Tool – Healthcare</strong></p><ul><li>Led architecture and end-to-end development of an AI-powered RFP management tool modeled after RFPIO and Loopio, tailored for Philips (healthcare domain)</li><li>Mentored two junior developers on React best practices and code review processes</li><li>Built a recursive section/subsection system with seamless drag-and-drop using Dnd Kit to manage complex RFP structures</li><li>Optimized frontend performance with deep memoization, API batching, and intelligent caching, reducing load times by 70%</li><li>Built high-performance virtualized lists with TanStack Virtualization handling 10,000+ rows</li><li>Implemented CI/CD saving 20% deployment time</li></ul><p><em>Tech: React 18, Filament, Context API, React Hook Form, YUP, Redux Toolkit, Github CI CD</em></p><p><strong>Contentful Experience Website</strong></p><ul><li>Led frontend revamp of healthcare content platform achieving 40% faster load times with Next.js and Contentful CMS</li><li>Resolved critical performance bottlenecks with code splitting, lazy loading, and intelligent caching</li><li>Improved stability and Core Web Vitals through SSR and advanced caching strategies</li></ul><p><em>Tech: Next.js 14, React 18, Vanilla Extract CSS, Context API</em></p>',
          bullets: [],
        },
        {
          id: 'exp2',
          company: 'Gloify',
          role: 'Software Engineer',
          location: '',
          startDate: '06/2023',
          endDate: '08/2024',
          current: false,
          description: '<p><strong>FinEase – Stock Market Trading Platform</strong></p><ul><li>Designed and implemented a brokerage platform using a scalable Next.js architecture with SSR, improving SEO and feature velocity</li><li>Engineered dynamic data visualizations with Chart.js, optimized with memoization and lazy loading for high-volume stock data</li><li>Defined modular Redux Toolkit state management patterns, accelerating feature development and maintainability</li></ul><p><em>Tech: Next.js, React 18, Material UI, Chart.js, SASS, Redux, CSS Modules</em></p><p><strong>Paywize – B2B FinTech Platform</strong></p><ul><li>Architected secure B2B payment platform with scalable architecture for financial transactions between merchants and distributors</li><li>Implemented JWT authentication and RBAC with multiple payment channels including UPI QR, Virtual Accounts, and Wallet transfers</li><li>Optimized APIs and frontend rendering to handle 1,000+ concurrent users with &lt;500ms response times</li></ul><p><em>Tech: React 18, Node.js, Express, Redux Toolkit, Material UI, YUP, React Hook Form</em></p>',
          bullets: [],
        },
        {
          id: 'exp3',
          company: 'TATA Consultancy Services',
          role: 'System Engineer',
          location: '',
          startDate: '02/2023',
          endDate: '06/2023',
          current: false,
          description: '<p><strong>Ingram Micro – E-commerce Platform</strong></p><ul><li>Modernized legacy frontend architecture for a high-traffic e-commerce platform, reducing load time by 25% and improving UX under high concurrency</li><li>Optimized complex forms and state management using Zustand and Context API for bulk order processing</li></ul><p><em>Tech: React 17, Context API, Bootstrap, Ant Design, CSS-in-JS</em></p>',
          bullets: [],
        },
        {
          id: 'exp4',
          company: 'Indegene Pvt Ltd',
          role: 'Junior Software Engineer',
          location: '',
          startDate: '10/2020',
          endDate: '02/2023',
          current: false,
          description: '<p><strong>Pfizer Projects – Healthcare Communication</strong></p><ul><li>Developed responsive healthcare applications and email templates using React, Bootstrap, and Veeva Vault for Pfizer initiatives</li><li>Delivered internal tools and static sites used for communication campaigns, improving efficiency for pharmaceutical reps</li><li>Recognized with "Best Sprinter" award three times for consistent, high-quality delivery under tight deadlines</li></ul><p><em>Tech: React.js, Bootstrap, Tailwind CSS, Veeva Vault, Salesforce</em></p><p><strong>Software Pundits (Contract @ Indegene)</strong></p><ul><li>Contributed to healthcare-based static sites and email template designs, building for multi-device compatibility</li></ul>',
          bullets: [],
        },
        {
          id: 'exp5',
          company: 'DigitalKnock India Pvt Ltd',
          role: 'Web Developer',
          location: '',
          startDate: '01/2019',
          endDate: '10/2020',
          current: false,
          description: '<p>Architected 20+ client-facing static websites from scratch using HTML, CSS, and JavaScript. Converted static sites into CMS-backed applications using PHP and MySQL. Ensured responsive design, cross-browser support, and performance optimization across devices.</p><p><em>Tech: HTML, CSS, JavaScript, Bootstrap, PHP, MySQL, Tailwind CSS</em></p>',
          bullets: [],
        },
      ],
    },
    {
      id: 'certifications',
      type: 'certifications',
      title: 'Certificates',
      settings: { spacing: 'normal', showDates: true },
      items: [
        {
          id: 'cert1',
          name: 'JavaScript Certification',
          issuer: 'Udemy',
          date: '',
          expiry: '',
          credentialId: '',
          url: '',
        },
        {
          id: 'cert2',
          name: 'Node.js Certification',
          issuer: 'Udemy',
          date: '',
          expiry: '',
          credentialId: '',
          url: '',
        },
      ],
    },
    {
      id: 'education',
      type: 'education',
      title: 'Education',
      settings: {
        spacing: 'normal',
        columns: 1,
        showDates: true,
        showLocation: false,
        titleStyle: 'stacked',
      },
      items: [
        {
          id: 'edu1',
          institution: 'Jawaharlal Nehru Technological University',
          degree: 'Pharmaceutical Engineering',
          fieldOfStudy: '',
          location: '',
          startDate: '05/2014',
          endDate: '06/2018',
          gpa: '',
          description: '',
          bullets: [],
        },
      ],
    },
  ],
  coverLetter: {
    recipientName: '',
    recipientTitle: 'Hiring Manager',
    company: '',
    date: '',
    subject: '',
    body: '',
    closing: 'Sincerely',
  },
};

// Factory functions to create a fresh empty section of each type.
// Each factory seeds one blank item so the section title appears in the canvas immediately.
export const SECTION_TYPE_DEFAULTS = {
  experience: (id) => ({
    id, type: 'experience', title: 'Experience',
    settings: { spacing: 'normal', columns: 1, showDates: true, showLocation: true, titleStyle: 'stacked' },
    items: [{ id: `${id}_item1`, company: '', role: '', location: '', startDate: '', endDate: '', current: false, description: '', bullets: [] }],
  }),
  education: (id) => ({
    id, type: 'education', title: 'Education',
    settings: { spacing: 'normal', columns: 1, showDates: true, showLocation: false, titleStyle: 'stacked' },
    items: [{ id: `${id}_item1`, institution: '', degree: '', fieldOfStudy: '', location: '', startDate: '', endDate: '', gpa: '', description: '', bullets: [] }],
  }),
  skills: (id) => ({
    id, type: 'skills', title: 'Skills',
    settings: { spacing: 'normal', columns: 1, skillsStyle: 'inline', separator: 'colon' },
    items: [{ id: `${id}_item1`, category: '', skills: '' }],
  }),
  projects: (id) => ({
    id, type: 'projects', title: 'Projects',
    settings: { spacing: 'normal', columns: 1, showDates: true, titleStyle: 'stacked' },
    items: [{ id: `${id}_item1`, name: '', url: '', technologies: '', startDate: '', endDate: '', description: '', bullets: [] }],
  }),
  languages: (id) => ({
    id, type: 'languages', title: 'Languages',
    settings: { spacing: 'normal', columns: 2 },
    items: [{ id: `${id}_item1`, language: '', proficiency: 'Professional' }],
  }),
  certifications: (id) => ({
    id, type: 'certifications', title: 'Certifications',
    settings: { spacing: 'normal', showDates: true, columns: 1 },
    items: [{ id: `${id}_item1`, name: '', issuer: '', date: '', expiry: '', credentialId: '', url: '' }],
  }),
  awards: (id) => ({
    id, type: 'awards', title: 'Awards & Honors',
    settings: { spacing: 'normal', showDates: true },
    items: [{ id: `${id}_item1`, title: '', issuer: '', date: '', description: '' }],
  }),
  volunteering: (id) => ({
    id, type: 'volunteering', title: 'Volunteering',
    settings: { spacing: 'normal', showDates: true, showLocation: true, titleStyle: 'stacked' },
    items: [{ id: `${id}_item1`, org: '', role: '', location: '', startDate: '', endDate: '', description: '', bullets: [] }],
  }),
  references: (id) => ({
    id, type: 'references', title: 'References',
    settings: { spacing: 'normal', columns: 2 },
    items: [{ id: `${id}_item1`, name: '', jobTitle: '', company: '', relationship: '', email: '', phone: '' }],
  }),
  interests: (id) => ({
    id, type: 'interests', title: 'Interests',
    settings: { spacing: 'normal' },
    items: [{ id: `${id}_item1`, interests: '' }],
  }),
  custom: (id) => ({
    id, type: 'custom', title: 'Custom Section',
    settings: { spacing: 'normal', columns: 1, titleStyle: 'stacked' },
    items: [{ id: `${id}_item1`, title: '', subtitle: '', date: '', location: '', description: '', bullets: [] }],
  }),
};
